stages:
  - sync

variables:
  # 在 GitLab 项目的 Settings -> CI/CD -> Variables 中配置 GITHUB_TOKEN
  GITHUB_TOKEN: $GITHUB_TOKEN
  SYNC_BRANCH: "main"
  # 禁用浅克隆，拉取完整历史
  GIT_DEPTH: 0

sync-to-github:
  stage: sync
  image:
    name: 10.144.233.86:8082/sang/bitnami/git:latest
    pull_policy: if-not-present
  tags:
    - docker
  variables:
    http_proxy: "http://192.168.1.13:7890"
    https_proxy: "http://192.168.1.13:7890"
    no_proxy: "127.0.0.1,localhost"
  script:
    # 添加 GitHub 远程
    - git remote add github https://saaangxy:${GITHUB_TOKEN}@github.com/saaangxy/HomiBook.git
    # 全量 fetch 所有分支
    - git fetch --all
    # 推送完整分支到 GitHub
    - git lfs push --all github main || true
    - git push -f github HEAD:main
  rules:
    - if: $CI_COMMIT_BRANCH == $SYNC_BRANCH
      when: always
  retry:
    max: 2
